# Generated by Django 5.1.1 on 2024-09-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='member_number',
            field=models.BigIntegerField(default=111111111, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
