# Generated by Django 5.1.1 on 2024-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_user_profile_email_user_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
