# Generated by Django 5.1.1 on 2024-10-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_profile_username'),
        ('subscriptions', '0008_remove_user_subscriptions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.user_subscriptions'),
        ),
    ]
