# Generated by Django 5.1.1 on 2024-10-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_remove_user_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='subscription',
        ),
    ]
