# Generated by Django 5.1.1 on 2024-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postcode',
            new_name='post_or_zipcode',
        ),
    ]
