# Generated by Django 5.1.1 on 2024-10-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_remove_order_country_remove_order_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='subscription',
        ),
    ]
