# Generated by Django 5.1.1 on 2024-10-12 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_subscription'),
        ('subscriptions', '0012_alter_subscription_info_for_user_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='subscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.user_subscriptions'),
            preserve_default=False,
        ),
    ]
