# Generated by Django 5.1.1 on 2024-10-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_orderlineitem_quantity_orderlineitem_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
