# Generated by Django 5.1.1 on 2024-09-20 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('world', 'World'), ('politics', 'Politics'), ('culture', 'Culture'), ('sport', 'Sport'), ('sci-tech', 'Science & Technology'), ('entertainment', 'Entertainment')], max_length=15)),
                ('friendly_name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=254)),
                ('headline', models.CharField(max_length=1024)),
                ('article_text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.URLField(max_length=1024)),
                ('image', models.ImageField(upload_to='')),
                ('image_description', models.CharField(max_length=254)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category')),
            ],
        ),
    ]
