# Generated by Django 5.1.1 on 2024-09-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_article_image_alter_article_image_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
    ]
