# Generated by Django 5.1.1 on 2024-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_article_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(db_index=True, max_length=1024),
        ),
    ]
