# Generated by Django 5.1.1 on 2024-10-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_article_article_text_alter_article_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
