# Generated by Django 5.1.1 on 2024-09-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=254)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.DecimalField(decimal_places=0, max_digits=4)),
                ('auto_renew', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
