# Generated by Django 5.1.1 on 2024-09-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='auto_renew',
        ),
        migrations.AlterField(
            model_name='user_subscriptions',
            name='duration',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
