# Generated by Django 5.1.1 on 2024-09-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('subscriptions', '0002_remove_user_subscriptions_auto_renew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscriptions',
            old_name='duration',
            new_name='duration_years',
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='auto_renew',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='duration_days',
            field=models.DecimalField(decimal_places=0, default=365, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='renew_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.user_profile'),
        ),
    ]
