# Generated by Django 5.1.1 on 2024-09-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('subscriptions', '0003_rename_duration_user_subscriptions_duration_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_subscriptions',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_subscriptions',
            name='image_description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user_subscriptions',
            name='duration_days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='user_subscriptions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.user_profile'),
        ),
    ]
