# Generated by Django 5.1.1 on 2024-09-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_user_subscriptions_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_subscriptions',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
