# Generated by Django 5.1.1 on 2024-09-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_user_subscriptions_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_subscriptions',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
            preserve_default=False,
        ),
    ]
