# Generated by Django 5.1.1 on 2024-09-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_user_subscriptions_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='vat',
        ),
    ]
