# Generated by Django 5.1.1 on 2024-10-01 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_user_subscriptions_total_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='user',
        ),
    ]
