# Generated by Django 5.1.1 on 2024-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_user_subscriptions_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_subscriptions',
            name='paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
