# Generated by Django 5.1.1 on 2024-10-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_user_subscriptions_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_subscriptions',
            old_name='type',
            new_name='subscription_type',
        ),
    ]
