# Generated by Django 5.1.1 on 2024-10-09 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_subscription'),
        ('profiles', '0007_remove_user_profile_subscription'),
        ('subscriptions', '0010_rename_type_user_subscriptions_subscription_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='auto_renew',
        ),
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='user_subscriptions',
            name='renew_date',
        ),
        migrations.CreateModel(
            name='Subscription_Info_For_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_renew', models.BooleanField(blank=True, default=False, null=True)),
                ('renew_date', models.DateTimeField(blank=True, null=True)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='checkout.order')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_chosen', to='subscriptions.user_subscriptions')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription_info', to='profiles.user_profile')),
            ],
        ),
    ]
