# Generated by Django 5.1.1 on 2024-10-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_remove_orderlineitem_subscription'),
        ('subscriptions', '0011_remove_user_subscriptions_auto_renew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_info_for_user',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='checkout.order'),
        ),
    ]
