# Generated by Django 5.1.1 on 2024-10-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_info_for_user_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_subscriptions',
            name='image_name',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
